spring.application.name=url-shortener-sb

#server configurations
server.port=9090

#DB configurations
spring.datasource.url=jdbc:mysql://localhost:3306/urlshotenerdb
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.show-sql=true


## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Hibernate ddl auto (create, create-drop, none, update)
spring.jpa.hibernate.ddl-auto=update

# jwt related configurations
security.jwt.secret-key=Vos9TCvo60vshJ2bTMACEUAOWmkfH9erkpMfo5OUAAB4N5ia6lSFNy89eumiS4aDGcmCrr53coVtCshbnr1JMQ==
security.jwt.expiration-time=3600000


# server node id
snowflake.config.node-id=10
