spring.application.name=url-shortener-sb
server.port=9090

#DB configurations
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.show-sql=true


## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Hibernate ddl auto (create, create-drop, none, update)
spring.jpa.hibernate.ddl-auto=update

# jwt related configurations
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME}


# server node id
snowflake.config.node-id=${SERVER_NODE_ID}

frontend.url=${FRONT_END_URL}
